# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint-and-test:
    name: Benchmarks
    runs-on: ubuntu-latest
    steps:

    # https://github.com/actions/setup-go
    - name: set up go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23.x"
        check-latest: true
        cache: false

    - name: Initialize
      run: |
        go install golang.org/x/perf/cmd/benchstat@latest
        rm -rf /tmp/bench/
        mkdir -p /tmp/bench/

    # https://github.com/actions/checkout
    - uses: actions/checkout@v4
      name: Checkout main
      with:
        ref: main

    - name: Benchmark main
      run: |
        rm -rf /tmp/bench.main.txt
        go test -benchtime=2s -count=6 -benchmem -run=^Benchmark$ -mod=readonly -bench=. ./... | tee /tmp/bench.main.txt

    # https://github.com/actions/checkout
    - uses: actions/checkout@v4
      name: Checkout PR HEAD

    - name: Benchmark head
      run: |
        rm -rf /tmp/bench.head.txt
        go test -benchtime=2s -count=6 -benchmem -run=^Benchmark$ -mod=readonly -bench=. ./... | tee /tmp/bench.head.txt

    - name: Compare benchmarks
      run: |
        benchstat /tmp/bench.main.txt /tmp/bench.head.txt | tee /tmp/summary.txt
        echo '# Benchmarks stats' >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        cat /tmp/summary.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
